#
###################################
# Site wide configuration
####################################
#
title: digaresc
email:
description: Diego Garcia personal blog
url: http://digaresc.info


#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Mexico
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Diego Iván García Escobedo
  avatar: personal.jpeg
  job: "personal blog"
  bio: "I like to solve problems and create things.<br>I'm very focused on creating relationships and generating movements."
  email: digaresc@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: digaresc
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: digaresc
  skype: #username
  xing: #username
  instagram: #username
  lastfm: digaresc
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
