# Site settings
title: digaresc.info
email: contact@digaresc.info
description: > # this means to ignore newlines until "baseurl:"
  I like to solve problems and create things
  I'm very focused on creating relationships and generating movements.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://digaresc.info" # the base hostname & protocol for your site
twitter_username: digaresc
github_username:  digaresc

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman